[package]
name = "afs-policy-simulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "afs-policy-simulator"
path = "src/main.rs"

[dependencies]
afs-common = { path = "../common" }
afs-policy-core = { path = "../policy-core" }
anyhow.workspace = true
clap.workspace = true
csv.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
